[scaffold]
version = "0.2.0"

[repos.lez]
source = "https://github.com/logos-blockchain/logos-execution-zone.git"
pin = "cf3639d8252040d13b3d4e933feb19b42c76e14a"

[repos.spel]
source = "https://github.com/logos-co/spel.git"
pin = "84f50d4aa473a70b72a16a7fb468c5618277cdd7"

[wallet]
home_dir = ".scaffold/wallet"

[framework]
kind = "default"
version = "0.1.0"

[framework.idl]
spec = "lssa-idl/0.1.0"
path = "artifacts"

[localnet]
port = 3040
risc0_dev_mode = true
