#ifndef TOKEN_FFI_H
#define TOKEN_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_program_id(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_decode_definition(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_decode_holding(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_decode_metadata(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_decode_account(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_create_fungible_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_create_fungible_with_metadata_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_create_non_fungible_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_initialize_holding_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_transfer_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_burn_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_mint_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_mint_with_authority_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_set_authority_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_set_authority_with_authority_plan(const char *request_json);

/**
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *token_print_nft_plan(const char *request_json);

/**
 * Releases a string returned by a `token_*` operation.
 *
 * # Safety
 * `value` must be null or a pointer returned by this library that has not been freed.
 */
void token_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TOKEN_FFI_H */
