#ifndef STABLECOIN_FFI_H
#define STABLECOIN_FFI_H

#pragma once

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Resolves the stablecoin program ID and derives all singleton account IDs.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_program_info(const char *request_json);

/**
 * Decodes and validates the singleton `ProtocolParameters` account.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_decode_protocol_parameters(const char *request_json);

/**
 * Decodes and validates the singleton `StabilityFeeAccumulator` account.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_decode_stability_fee_accumulator(const char *request_json);

/**
 * Decodes and validates the singleton `RedemptionPriceState` account.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_decode_redemption_price_state(const char *request_json);

/**
 * Validates stablecoin global accounts and projects their current values at `CLOCK_01`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_current_global_state(const char *request_json);

/**
 * Quotes the next redemption-rate controller update without submitting it.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_redemption_rate_update_quote(const char *request_json);

/**
 * Builds the exact wallet submission plan for `AccrueStabilityFee`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_accrue_stability_fee_plan(const char *request_json);

/**
 * Builds a preflighted wallet submission plan for `UpdateRedemptionRate`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_update_redemption_rate_plan(const char *request_json);

/**
 * Builds the best-effort wallet submission plan for `RefreshGlobals`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_refresh_globals_plan(const char *request_json);

/**
 * Builds the exact wallet submission plan for `InitializeProgram`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_initialize_program_plan(const char *request_json);

/**
 * Builds the exact wallet submission plan for `OpenPosition`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_open_position_plan(const char *request_json);

/**
 * Derives a position and its collateral vault from owner and nonce.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_position_addresses(const char *request_json);

/**
 * Builds the exact wallet submission plan for `DepositCollateral`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_deposit_collateral_plan(const char *request_json);

/**
 * Builds a preflighted wallet submission plan for `RepayDebt`.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_repay_debt_plan(const char *request_json);

/**
 * Quotes position health using validated live state and wide arithmetic.
 *
 * # Safety
 * `request_json` must be null or point to a live NUL-terminated byte string.
 */
char *stablecoin_position_health(const char *request_json);

/**
 * Releases a string returned by a `stablecoin_*` operation.
 *
 * # Safety
 * `value` must be null or a pointer returned by this library that has not been freed.
 */
void stablecoin_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* STABLECOIN_FFI_H */
