#include "stablecoin_module_impl.h"
#include "stablecoin_module_support.h"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <iterator>
#include <memory>
#include <mutex>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

// Generated by logos-module-builder. Kept out of the universal API header.
#include "logos_sdk.h"

extern "C" {
#include "stablecoin_ffi.h"
}

namespace {

using json = nlohmann::json;

constexpr char STABLECOIN_PROGRAM_BIN_ENV[] = "STABLECOIN_PROGRAM_BIN";
constexpr char STABLECOIN_PROGRAM_ID_ENV[] = "STABLECOIN_PROGRAM_ID";
std::mutex programInfoMutex;

bool stablecoinDebug() {
    static const bool enabled = std::getenv("STABLECOIN_DEBUG") != nullptr;
    return enabled;
}

#define STABLECOIN_TRACE(message)                                                   \
    do {                                                                            \
        if (stablecoinDebug()) std::cerr << "[stablecoin-debug] " << message << '\n'; \
    } while (false)

std::string trim(const std::string& value) {
    std::size_t begin = 0;
    std::size_t end = value.size();
    while (begin < end && std::isspace(static_cast<unsigned char>(value[begin]))) ++begin;
    while (end > begin && std::isspace(static_cast<unsigned char>(value[end - 1]))) --end;
    return value.substr(begin, end - begin);
}

std::string jsonString(const json& object, const char* key) {
    const auto field = object.find(key);
    return field != object.end() && field->is_string()
        ? field->get<std::string>()
        : std::string();
}

std::string bytesToHex(const std::uint8_t* bytes, std::size_t length) {
    static constexpr char digits[] = "0123456789abcdef";
    std::string result;
    result.reserve(length * 2);
    for (std::size_t index = 0; index < length; ++index) {
        result.push_back(digits[bytes[index] >> 4]);
        result.push_back(digits[bytes[index] & 0x0f]);
    }
    return result;
}

LogosMap publicOk() {
    return {{"status", "ok"}, {"error", ""}};
}

LogosMap publicError(const std::string& error) {
    return {{"status", "error"}, {"error", error}};
}

template <typename Operation>
LogosMap guarded(Operation&& operation) noexcept {
    try {
        return operation();
    } catch (const std::exception& error) {
        STABLECOIN_TRACE("caught exception: " << error.what());
    } catch (...) {
        STABLECOIN_TRACE("caught non-standard exception");
    }
    return publicError("backend_error");
}

struct FfiResult {
    bool ok = false;
    json value;
    std::string error;
};

FfiResult callStablecoin(char* (*operation)(const char*), const json& request) {
    const std::string payload = request.dump();
    std::unique_ptr<char, decltype(&stablecoin_free)> response(
        operation(payload.c_str()),
        &stablecoin_free);
    if (!response) {
        STABLECOIN_TRACE("stablecoin_ffi returned null");
        return {};
    }

    const json document = json::parse(response.get(), nullptr, false);
    if (!document.is_object()) {
        STABLECOIN_TRACE("stablecoin_ffi returned malformed JSON");
        return {};
    }
    const auto ok = document.find("ok");
    if (ok == document.end() || !ok->is_boolean()) return {};
    if (!ok->get<bool>()) {
        const std::string error = jsonString(document, "error");
        STABLECOIN_TRACE("stablecoin_ffi failure: " << error);
        return {false, json(), error};
    }
    const auto value = document.find("value");
    if (value == document.end() || !value->is_object()) return {};
    return {true, *value, {}};
}

bool hasString(const json& object, const char* key) {
    const auto field = object.find(key);
    return field != object.end() && field->is_string();
}

}  // namespace

std::vector<std::uint8_t> StablecoinModuleImpl::loadStablecoinBinary() const {
    const char* path = std::getenv(STABLECOIN_PROGRAM_BIN_ENV);
    if (path == nullptr || *path == '\0') return {};
    std::ifstream file(path, std::ios::binary);
    if (!file) return {};
    return std::vector<std::uint8_t>(std::istreambuf_iterator<char>(file),
                                     std::istreambuf_iterator<char>());
}

nlohmann::json StablecoinModuleImpl::stablecoinProgramInfo(std::string& error) {
    const std::lock_guard<std::mutex> lock(programInfoMutex);
    if (programInfoResolved_) {
        const json cached = json::parse(programInfoJson_, nullptr, false);
        if (cached.is_object()) return cached;
        programInfoResolved_ = false;
        programInfoJson_.clear();
    }

    const char* configured_value = std::getenv(STABLECOIN_PROGRAM_ID_ENV);
    const char* binary_path = std::getenv(STABLECOIN_PROGRAM_BIN_ENV);
    const std::string configured = configured_value == nullptr
        ? std::string()
        : trim(configured_value);
    const bool program_id_configured = !configured.empty();
    const bool binary_configured = binary_path != nullptr && *binary_path != '\0';
    if (!program_id_configured && !binary_configured) {
        error = "config_missing";
        return json();
    }

    json request = json::object();
    if (program_id_configured) {
        const std::string normalized = normalizeAccountId(configured);
        if (normalized.empty()) {
            error = "invalid_program_id";
            return json();
        }
        request["stablecoinProgramId"] = normalized;
    }

    if (binary_configured) {
        const std::vector<std::uint8_t> binary = loadStablecoinBinary();
        if (binary.empty()) {
            error = "invalid_program_binary";
            return json();
        }
        request["elf"] = bytesToHex(binary.data(), binary.size());
    }

    const FfiResult result = callStablecoin(stablecoin_program_info, request);
    if (!result.ok) {
        error = stablecoin_module::detail::stableFfiError(result.error);
        return json();
    }

    static constexpr const char* required_fields[] = {
        "programId",
        "programIdHex",
        "protocolParametersId",
        "protocolParametersIdHex",
        "stabilityFeeAccumulatorId",
        "stabilityFeeAccumulatorIdHex",
        "redemptionPriceStateId",
        "redemptionPriceStateIdHex",
        "stablecoinDefinitionId",
        "stablecoinDefinitionIdHex",
        "stablecoinMasterHoldingId",
        "stablecoinMasterHoldingIdHex",
        "clockId",
        "clockIdHex",
    };
    if (std::any_of(std::begin(required_fields), std::end(required_fields), [&](const char* key) {
            return !hasString(result.value, key) || jsonString(result.value, key).empty();
        })) {
        error = "backend_error";
        return json();
    }

    programInfoJson_ = result.value.dump();
    programInfoResolved_ = true;
    return result.value;
}

std::string StablecoinModuleImpl::normalizeAccountId(const std::string& id) {
    return stablecoin_module::detail::normalizeAccountId(
        id,
        [this](const std::string& base58) {
            return modules().lez_core.account_id_from_base58(base58);
        });
}

nlohmann::json StablecoinModuleImpl::readPublicAccount(const std::string& account_id) {
    logos::CallError call_error;
    const std::string raw =
        modules().lez_core.get_account_public(account_id, &call_error);
    if (!call_error.ok()) {
        STABLECOIN_TRACE(
            "lez_core account read transport failure: " << call_error.code);
        return {{"id", account_id}, {"status", "backend_error"}};
    }
    return stablecoin_module::detail::publicAccountRead(account_id, raw);
}

bool StablecoinModuleImpl::requireUninitialized(const std::string& account_id,
                                                std::string& error) {
    const json read = readPublicAccount(account_id);
    const std::string status = jsonString(read, "status");
    if (status == "not_found") return true;
    error = status == "ok" ? "already_initialized" : "account_read_failed";
    return false;
}

LogosMap StablecoinModuleImpl::programInfo() {
    return guarded([&]() -> LogosMap {
        std::string error;
        const json info = stablecoinProgramInfo(error);
        if (!info.is_object()) return publicError(error.empty() ? "backend_error" : error);

        LogosMap result = publicOk();
        for (auto field = info.begin(); field != info.end(); ++field) {
            result[field.key()] = field.value();
        }
        return result;
    });
}

LogosMap StablecoinModuleImpl::protocolParameters() {
    return guarded([&]() -> LogosMap {
        std::string error;
        const json info = stablecoinProgramInfo(error);
        if (!info.is_object()) return publicError(error.empty() ? "backend_error" : error);

        const json read = readPublicAccount(jsonString(info, "protocolParametersIdHex"));
        const std::string status = jsonString(read, "status");
        if (status == "not_found") return publicError("not_initialized");
        if (status != "ok") return publicError("account_read_failed");

        const FfiResult decoded = callStablecoin(stablecoin_decode_protocol_parameters, {
            {"stablecoinProgramId", info["programIdHex"]},
            {"protocolParameters", read},
        });
        if (!decoded.ok) {
            return publicError(stablecoin_module::detail::stableFfiError(decoded.error));
        }

        LogosMap result = publicOk();
        result["protocolParameters"] = decoded.value;
        return result;
    });
}

LogosMap StablecoinModuleImpl::submitPlan(const nlohmann::json& plan) {
    const auto accounts_field = plan.find("accountIds");
    const auto signers_field = plan.find("signingRequirements");
    const auto instruction_field = plan.find("instruction");
    const std::string program_id = jsonString(plan, "programId");
    if (accounts_field == plan.end() || !accounts_field->is_array()
        || signers_field == plan.end() || !signers_field->is_array()
        || instruction_field == plan.end()
        || !stablecoin_module::detail::isValidAccountIdHex(program_id)) {
        return publicError("backend_error");
    }

    const std::vector<std::string> account_ids =
        accounts_field->get<std::vector<std::string>>();
    const std::vector<bool> signing_requirements =
        signers_field->get<std::vector<bool>>();
    const std::vector<std::uint8_t> instruction =
        stablecoin_module::detail::jsonInstructionLeBytes(*instruction_field);
    if (account_ids.size() != 9 || signing_requirements.size() != 9
        || !std::all_of(account_ids.begin(), account_ids.end(),
                        stablecoin_module::detail::isValidAccountIdHex)
        || signing_requirements != std::vector<bool>({true, false, false, false, false,
                                                      false, false, false, false})
        || instruction.empty()) {
        return publicError("backend_error");
    }

    logos::CallError call_error;
    const std::string raw = modules().lez_core.send_generic_public_transaction(
        account_ids,
        signing_requirements,
        instruction,
        program_id,
        &call_error);
    if (!call_error.ok()) {
        STABLECOIN_TRACE(
            "lez_core submission transport failure: " << call_error.code);
        return publicError("wallet_submission_failed");
    }

    const std::string transaction_id = stablecoin_module::detail::transactionId(raw);
    if (transaction_id.empty()) return publicError("wallet_submission_failed");
    LogosMap result = publicOk();
    result["transactionId"] = transaction_id;
    return result;
}

LogosMap StablecoinModuleImpl::initializeProgram(const LogosMap& request) {
    return guarded([&]() -> LogosMap {
        if (!request.is_object()) return publicError("bad_request");
        for (const char* key : {
                 "adminId",
                 "freezeAuthorityId",
                 "collateralDefinitionId",
                 "marketPriceOracleId",
                 "stablecoinName",
             }) {
            if (!hasString(request, key)) return publicError("bad_request");
        }
        for (const char* key : {
                 "initialStabilityFeePerMillisecond",
                 "initialControllerProportionalGain",
                 "initialControllerIntegralGain",
                 "initialMinimumCollateralizationRatio",
                 "minimumMillisecondsBetweenRateUpdates",
                 "maximumOraclePriceAgeMilliseconds",
                 "initialRedemptionPrice",
             }) {
            if (request.find(key) == request.end()) return publicError("bad_request");
        }

        std::string error;
        const json info = stablecoinProgramInfo(error);
        if (!info.is_object()) return publicError(error.empty() ? "backend_error" : error);

        const std::string admin = normalizeAccountId(jsonString(request, "adminId"));
        const std::string freeze_authority =
            normalizeAccountId(jsonString(request, "freezeAuthorityId"));
        const std::string collateral =
            normalizeAccountId(jsonString(request, "collateralDefinitionId"));
        const std::string oracle =
            normalizeAccountId(jsonString(request, "marketPriceOracleId"));
        if (admin.empty() || freeze_authority.empty() || collateral.empty() || oracle.empty()) {
            return publicError("invalid_account_id");
        }

        for (const char* key : {
                 "protocolParametersIdHex",
                 "stabilityFeeAccumulatorIdHex",
                 "redemptionPriceStateIdHex",
                 "stablecoinDefinitionIdHex",
                 "stablecoinMasterHoldingIdHex",
             }) {
            if (!requireUninitialized(jsonString(info, key), error)) return publicError(error);
        }

        const json collateral_read = readPublicAccount(collateral);
        const json oracle_read = readPublicAccount(oracle);
        const json clock_read = readPublicAccount(jsonString(info, "clockIdHex"));
        if (jsonString(collateral_read, "status") != "ok"
            || jsonString(oracle_read, "status") != "ok"
            || jsonString(clock_read, "status") != "ok") {
            return publicError("account_read_failed");
        }

        const FfiResult planned = callStablecoin(stablecoin_initialize_program_plan, {
            {"stablecoinProgramId", info["programIdHex"]},
            {"adminId", admin},
            {"freezeAuthorityId", freeze_authority},
            {"collateralDefinition", collateral_read},
            {"marketPriceOracle", oracle_read},
            {"clock", clock_read},
            {"initialStabilityFeePerMillisecond",
             request["initialStabilityFeePerMillisecond"]},
            {"initialControllerProportionalGain",
             request["initialControllerProportionalGain"]},
            {"initialControllerIntegralGain", request["initialControllerIntegralGain"]},
            {"initialMinimumCollateralizationRatio",
             request["initialMinimumCollateralizationRatio"]},
            {"minimumMillisecondsBetweenRateUpdates",
             request["minimumMillisecondsBetweenRateUpdates"]},
            {"maximumOraclePriceAgeMilliseconds",
             request["maximumOraclePriceAgeMilliseconds"]},
            {"initialRedemptionPrice", request["initialRedemptionPrice"]},
            {"stablecoinName", request["stablecoinName"]},
        });
        if (!planned.ok) {
            return publicError(stablecoin_module::detail::stableFfiError(planned.error));
        }
        if (jsonString(planned.value, "programId") != jsonString(info, "programIdHex")) {
            return publicError("backend_error");
        }
        return submitPlan(planned.value);
    });
}
