//! Host-side embedding of the token-mint-authority RISC Zero guest ELF.
//!
//! Re-exports the constants produced by `build.rs` via `risc0_build::embed_methods` —
//! `TOKEN_MINT_AUTHORITY_ELF`, `TOKEN_MINT_AUTHORITY_PATH`, and `TOKEN_MINT_AUTHORITY_ID` — used by
//! host code to load and identify the guest binary.

#![allow(
    missing_docs,
    reason = "constants below are generated by risc0_build::embed_methods at build time"
)]

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
