#ifndef AMM_CLIENT_H
#define AMM_CLIENT_H

#pragma once

/* Generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

char *amm_config_id(const char *request_json);

char *amm_token_ids(const char *request_json);

char *amm_pair_ids(const char *request_json);

char *amm_context(const char *request_json);

char *amm_quote(const char *request_json);

char *amm_plan(const char *request_json);

char *amm_swap_pair(const char *request_json);

char *amm_resolve_pool(const char *request_json);

char *amm_swap_plan(const char *request_json);

char *amm_program_id(const char *request_json);

/**
 * Releases a string returned by an `amm_*` operation.
 *
 * # Safety
 * `value` must be null or a pointer returned by this library that has not been freed.
 */
void amm_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AMM_CLIENT_H */
